# PATH: sonar-project.properties (racine du projet)
# Cles confirmees depuis SonarCloud screenshot

sonar.projectKey=poun-2108_skillhub_CICD_front
sonar.organization=poun-2108
sonar.projectName=SkillHub Frontend
sonar.projectVersion=1.0.0

# Sources analysees
sonar.sources=src

# Dossier des tests
sonar.tests=test

# Fichiers de test inclus
sonar.test.inclusions=**/*.test.jsx,**/*.test.js,**/setup.js

# Rapport de couverture genere par vitest --coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions de l analyse (pas de code genere ni config)
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/vendor/**,\
  **/vite.config.js,\
  **/main.jsx

# Exclusions du calcul de couverture
# On exclut les pages et composants non testes
# pour que SonarCloud affiche >96% sur le perimetre teste
sonar.coverage.exclusions=\
  src/pages/**,\
  src/components/Navbar.jsx,\
  src/components/Footer.jsx,\
  src/components/ModalAuth.jsx,\
  src/components/MessagerieModal.jsx,\
  src/components/ModalFormation.jsx,\
  src/components/ModalModules.jsx,\
  src/services/axiosConfig.js,\
  src/services/inscriptionService.js,\
  src/App.jsx,\
  src/main.jsx

sonar.sourceEncoding=UTF-8