# PATH: sonar-project.properties (racine du projet)
# IMPORTANT : changer la branche principale dans SonarCloud UI
# Administration > Branches and Pull Requests > main branch = "main"

sonar.projectKey=poun-2108_skillhub_CICD_front
sonar.organization=poun-2108
sonar.projectName=SkillHub Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.test.jsx,**/*.test.js,**/setup.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/vendor/**,\
  **/vite.config.js,\
  **/main.jsx

sonar.coverage.exclusions=\
  src/pages/**,\
  src/components/Navbar.jsx,\
  src/components/Footer.jsx,\
  src/components/ModalAuth.jsx,\
  src/components/MessagerieModal.jsx,\
  src/components/ModalFormation.jsx,\
  src/components/ModalModules.jsx,\
  src/services/axiosConfig.js,\
  src/services/inscriptionService.js,\
  src/App.jsx,\
  src/main.jsx

sonar.sourceEncoding=UTF-8